name: Publish to MyGet

on:
  push:
    branches:
      - develop
      - uno_winui

jobs:
  build:

    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v2

    - name: Install .NET SDK 6.0.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Build with dotnet
      run: |
        dotnet build 'src\\Elmish.Uno.sln' -c Release -p:Platform='Any CPU' -maxcpucount

    - name: Pack Elmish.Uno with NuGet
      run: |
        $nuspec = get-content 'Elmish.Uno.nuspec' | %{ $_ -replace '\$versionSuffix\$',"-ci-${Env:GITHUB_RUN_ID}"}
        set-content 'Elmish.Uno.nuspec' -value $nuspec
        nuget pack 'Elmish.Uno.nuspec' -Properties Configuration=Release

    #- name: Pack Templates with NuGet
    #  run: |
    #    $nuspec = get-content 'src\\Templates\\Templates.nuspec' | %{ $_ -replace '\$versionSuffix\$',"-ci-${Env:GITHUB_RUN_ID}"}
    #    set-content 'src\\Templates\\Templates.nuspec' -value $nuspec
    #    nuget pack 'src\\Templates\\Templates.nuspec' -Properties Configuration=Release -NoDefaultExcludes

    - name: Publish to MyGet
      run: |
        dotnet nuget push -s 'https://www.myget.org/F/elmish_uno/api/v3/index.json' -k ${{secrets.MyGet_Key}} *.nupkg
