name: publish to MyGet

on:
  push:
    branches:
      - develop

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.200
        
    - name: Setup MSBuild.exe
      uses: warrenbuckley/Setup-MSBuild@v1
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
    
    - uses: nuget/setup-nuget@v1
      with:
        nuget-version: '5.x'
    
    - name: Restore NuGet Packages
      run: |
        nuget restore 'src\\Elmish.Uno.sln' -ConfigFile 'NuGet.Config'
        
    - name: Build with dotnet
      run: |
        msbuild 'src\\Elmish.Uno.sln' /t:Rebuild /p:Configuration=Release /p:Platform="Any CPU"
        $nuspec = get-content 'Elmish.Uno.nuspec' | %{ $_ -replace '\$versionSuffix\$',"-ci-${Env:GITHUB_RUN_ID}"} 
        set-content 'Elmish.Uno.nuspec' -value $nuspec
        nuget pack 'Elmish.Uno.nuspec' -Properties Configuration=Release
        
    - name: MyGet push
      run: |
        dotnet nuget push -s 'https://www.myget.org/F/elmish_uno/api/v3/index.json' -k ${{secrets.MyGet_Key}} *.nupkg
