name: Pull Request

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  build:

    runs-on: windows-2022

    steps:

    - uses: actions/checkout@v2

    - name: Install .NET SDK 6.0.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Install MSBuild
      uses: microsoft/setup-msbuild@v1.1
      with:
        #vs-version: '[17.0,)'
        vs-prerelease: true
        msbuild-architecture: x64

    - name: Build with dotnet
      run: |
        dotnet build 'src\\Elmish.Uno.sln' -c Release -p:Platform='Any CPU' -maxcpucount

    - name: Test
      run: dotnet test --no-build --configuration Release src/Elmish.Uno.Tests/Elmish.Uno.Tests.fsproj
